server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://andersongianotti:<db_password>@cluster0.gdebxo0.mongodb.net/?appName=Cluster0
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: grupo-mensagens
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.value.default.type: com.example.rabbitkafkaconsumer.model.Message
      spring.json.trusted.packages: "com.example.rabbitkafkaconsumer.model"